name: Simple CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Flask
      run: pip install flask
    
    - name: Run simple test
      run: python test_simple.py
    
    - name: Check app runs
      run: |
        python app/main.py &
        sleep 3
        echo "App started successfully!"
